// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGHmLwPMLxnEYd-Z97_UIsAI8Elc53M3c',
    appId: '1:782198909758:web:6032c46b0a75617c355a6f',
    messagingSenderId: '782198909758',
    projectId: 'ytapp-6c86f',
    authDomain: 'ytapp-6c86f.firebaseapp.com',
    storageBucket: 'ytapp-6c86f.appspot.com',
    measurementId: 'G-2155B71L3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6shNDaVg9IT8xTIHAxBE-0c1qTneThys',
    appId: '1:782198909758:android:453e1ccd430dd8fc355a6f',
    messagingSenderId: '782198909758',
    projectId: 'ytapp-6c86f',
    storageBucket: 'ytapp-6c86f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkItCEjfItuzj1iFYAuE1_kysccNul0Ek',
    appId: '1:782198909758:ios:16c50901f15fa4d0355a6f',
    messagingSenderId: '782198909758',
    projectId: 'ytapp-6c86f',
    storageBucket: 'ytapp-6c86f.appspot.com',
    iosBundleId: 'com.example.messageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkItCEjfItuzj1iFYAuE1_kysccNul0Ek',
    appId: '1:782198909758:ios:9401ff2ca2c37b67355a6f',
    messagingSenderId: '782198909758',
    projectId: 'ytapp-6c86f',
    storageBucket: 'ytapp-6c86f.appspot.com',
    iosBundleId: 'com.example.messageApp.RunnerTests',
  );
}
